title: Roberto Tamburini
description: DevOps Engineer & Photographer
theme: jekyll-theme-minimal
locale: en
show_downloads: false

# Enable posts
collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "portfolio.md"
    values:
      layout: portfolio

plugins:
  - jekyll-feed
